name: Build kernel (plain)
on:
  #schedule:
    #- cron: '0 4 * * *'  # Runs every day at 04:00 UTC
  workflow_dispatch: # Allow manual trigger if needed
  #push:
    #paths:
      #- '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4 

      - name: Install dependencies
        run: | 


